version: "3"

services:

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - 9000:9000
    depends_on: 
      - server

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - /data/db